version: 43.0.9
pageUuid: c37676ba-116f-11ea-b17d-d7734e1526f2
appTemplate:
  urlFragmentDefinitions:
    - ordered:
        - name: search
        - value: '{{ textinput1.value}}'
  appThemeId: null
  pageLoadValueOverrides:
    - ordered:
        - name: textinput1.value
        - value: '{{ urlparams.hash.search}}'
  customDocumentTitle: ''
  isGlobalWidget: false
  isFetching: true
  instrumentationEnabled: false
  customDocumentTitleEnabled: false
  version: 2.64.83
  responsiveLayoutDisabled: false
  createdAt: null
  loadingIndicatorsDisabled: false
