version: 43.0.9
pageUuid: fa9fa5be-72f6-11eb-b21e-ef9b4e886f33
appTemplate:
  urlFragmentDefinitions: []
  appThemeId: null
  preloadedAppJavaScript: null
  pageLoadValueOverrides: []
  customDocumentTitle: ''
  isGlobalWidget: false
  isFetching: false
  instrumentationEnabled: false
  customDocumentTitleEnabled: false
  preloadedAppJSLinks:
    array: []
  version: 2.66.25
  responsiveLayoutDisabled: false
  createdAt: null
  loadingIndicatorsDisabled: false
