version: 43.0.9
pageUuid: b33e60c0-116d-11ea-8c85-a368dd700d7c
appTemplate:
  urlFragmentDefinitions: []
  appThemeId: null
  pageLoadValueOverrides: []
  customDocumentTitle: ''
  isGlobalWidget: false
  isFetching: false
  instrumentationEnabled: false
  customDocumentTitleEnabled: false
  version: 2.53.7
  responsiveLayoutDisabled: false
  createdAt: null
  loadingIndicatorsDisabled: false
