version: 43.0.9
pageUuid: f28ab2fc-b890-11ec-bc7e-dba0c40aa69c
appTemplate:
  experimentalPerfFeatures:
    object:
      batchCommitModelEnabled: false
  rootScreen: tabscreen
  isMobileApp: true
  version: 2.90.6
  multiScreenMobileApp: true
  markdownLinkBehavior: auto
