version: 43.0.9
pageUuid: 7ff8e8ec-9bce-11eb-8e2f-5b213ff64690
appTemplate:
  urlFragmentDefinitions: []
  appStyles: ''
  appThemeId: null
  preloadedAppJavaScript: null
  pageLoadValueOverrides: []
  customDocumentTitle: ''
  isGlobalWidget: true
  isFetching: false
  instrumentationEnabled: false
  customDocumentTitleEnabled: false
  preloadedAppJSLinks:
    array: []
  version: 2.67.2
  responsiveLayoutDisabled: false
  createdAt: null
  loadingIndicatorsDisabled: false
